### PR TITLE
fix issues 4

### PR DESCRIPTION
**Pull request by li-yechao**

### CODE REVIEW

**Comment by silentcloud** [comment]
You want multiple dialog support? If so, notice https://github.com/react-component/m-dialog/blob/master/src/DialogWrap.tsx#L79, new dialog  will replace old dialog content

**Comment by li-yechao** [comment]
yes, When opening a new dialog, the original happens to be hidden, May be able to join man-made control

**Comment by li-yechao** [comment]
I can use difference prefixCls props to show multiple dialog!

**Comment by silentcloud** [comment]
@unordered Thanks, but close for https://github.com/react-component/m-dialog/commit/8bd2739f0dc7ade426c2d2c4aa21e6b7f178ddba

**Pull request closed without merging**
